
services:
  postgres:
    image: postgres:16.3
    hostname: postgres
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: produto
    networks:
      - produto-network

  produtos:
    build:
      context: ../../..
      dockerfile: Dockerfile
    hostname: produtos
    container_name: produtos
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - produto-network


networks:
  produto-network:

