
services:
  postgres:
    image: postgres:16.3
    hostname: produto
    container_name: produto
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: produto
    networks:
      - library-network

  pgadmin4:
    image: dpage/pgadmin4:8.9
    container_name: pgadmin4
    ports:
      - "15432:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    networks:
      - produto-network

networks:
  produto-network:

